apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocdiudemo
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      app=docker.io/huntergohil2/argocdimageupdaterexperimenthg
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-commit-message: "build: automatic update of {{.AppName}}"
spec:
  project: default
  source:
    repoURL: https://github.com/huntergohil/argoimageupdaterdemo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
